on: push

jobs:
  build_and_validate_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install CI dependencies
        run: |
          pip install nox pycobertura
      - name: Run linter
        run: |
          nox -s linter
      - name: Run tests
        run: |
          nox -s tests
      - name: Check coverage
        run: |
          nox -s coverage
      - name: Build documentation
        run: |
          nox -s docs
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: docs/_build
  publish_docs:
    runs-on: ubuntu-latest
    needs: build_and_validate_image
    if: github.ref == 'refs/heads/master'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: docs
          path: docs/_build
      - name: Publish documentation
        run: |
          nox -s docs --publish
